---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vm_name: "Test"
    vcenter_hostname: "vctr-vd01.sig.oregonstate.edu"
    vcenter_user: "sig_capstone_pu@onid.oregonstate.edu"
    vcenter_password: "<password>"
    vcenter_dc: "dc1"
    tag_name: "Managed-VM"
    tag_op: "tag"

  - name: Get facts about tag
    vmware_tag_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
    register: tag


  - name: Get tag id
    set_fact:
      tag_id: "{{ item.value.tag_id }}"
    when: item.key == tag_name
    with_dict: "{{ tag.tag_facts }}"
    register: tag_id

  

  - name: Tag vm
    command: ./tag_op.py {{ tag_op }} {{ tag_id }} {{ vm_name }}
